<%
require 'yaml'
formula = YAML.load_file('FORMULA')
formula_name = formula['name']
%>
---

driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

provisioner:
  name: salt_solo
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_install: bootstrap
  salt_bootstrap_options: -X git v2017.7.5
  salt_version: '2017.7.5'
  formula: <%= formula_name %>
  require_chef: false
  data_path: test/shared
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'debug' %>
  pillars-from-files:
    <%= formula_name %>.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

platforms:
  - name: centos-7
  - name: ubuntu-16.04
  - name: debian-9
  - name: freebsd-11
    driver:
      name: vagrant
      hostname: freebsd.ci.local
      cache_directory: false

suites:
  - name: default

  - name: apache_norestart
    provisioner:
      state_top:
        base:
          '*':
            - <%= formula_name %>
      pillars:
        apache.sls:
          apache:
            manage_service_states: false

  - name: bsd
    excludes:
      - name: centos-7
      - name: ubuntu-16.04
      - name: debian-9
    provisioner:
      state_top:
        base:
          '*':
            - <%= formula_name %>
            - <%= formula_name %>.config
            - <%= formula_name %>.mod_info
            - <%= formula_name %>.modules
